// background.js

// Set your Gemini API key here
const GEMINI_API_KEY = 'AIzaSyDSU-N3cZ168XVbNSTrH-rmWtYKZS-4GwE';

// Listen for extension updates
chrome.runtime.onUpdateAvailable.addListener(function(details) {
    console.log("Update available: " + details.version);
  });
  
  // Handle incoming messages
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    console.log("Background script received message:", request);
    
    if (request.action === 'callGeminiAPI') {
      console.log("Processing API call request from tab:", sender.tab ? sender.tab.id : "unknown");
      
      // We need to return true here to use sendResponse asynchronously
      callGeminiAPI(request.prompt)
        .then(result => {
          console.log("API call successful");
          try {
            sendResponse({ success: true, result: result });
          } catch (error) {
            console.error("Error sending response:", error);
          }
        })
        .catch(error => {
          console.error("API call failed:", error);
          try {
            sendResponse({ 
              success: false, 
              error: error.message || "Unknown error" 
            });
          } catch (responseError) {
            console.error("Error sending error response:", responseError);
          }
        });
      
      // This return true is CRUCIAL for asynchronous sendResponse
      return true;
    }
  });
  
  async function callGeminiAPI(prompt) {
    console.log("Calling Gemini API...");
    
    try {
      // Use static API key
      const apiKey = GEMINI_API_KEY;
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;
      
      console.log("Making fetch request to Gemini API");
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.2,
            maxOutputTokens: 1024
          }
        })
      });
      
      console.log("Fetch response status:", response.status);
      
      if (!response.ok) {
        const errorData = await response.json();
        console.error("API error details:", errorData);
        throw new Error(errorData.error?.message || `API request failed with status ${response.status}`);
      }
      
      const responseData = await response.json();
      
      // Extract the text from the response
      const generatedText = responseData.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No text was generated by the API');
      }
      
      return generatedText;
    } catch (error) {
      console.error("Fetch error:", error);
      throw error;
    }
  }
  
  // Add a listener for when the extension is installed
  chrome.runtime.onInstalled.addListener(function() {
    console.log("Extension installed");
  });
  
  // Handle extension startup
  chrome.runtime.onStartup.addListener(function() {
    console.log("Extension starting up");
  });